apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: mongodb-test
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cluster-storage-class
  local:
    path: /mnt/data/mongodb  # Is path ko apne node ke storage path se replace kar sakte hain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-192-168-40-115.ap-south-1.compute.internal  # Aap isme dono nodes ka naam add kar sakte hain
                - ip-192-168-94-126.ap-south-1.compute.internal
