apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: mongodb-test 
type: Opaque
data:
  MONGO_USER: a2FseWFuZGFkbWlu  # base64 encoded 'jannatadmin'
  MONGO_PASSWORD: a2FseWFuZDEyMw==  # base64 encoded 'jannat123'
